alias gpo="git push origin"
alias gs="git status"
alias gA="git add -A"
alias gcm="git commit -m"
alias gfo="git fetch origin"
alias gpom="git pull origin master"
alias gprom="git pull --rebase origin master"
alias gAcm="git add -A; git commit -m"
